# Generated by Django 5.0.7 on 2024-08-06 05:05

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.contrib.routable_page.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        ("wagtailcore", "0095_query_searchpromotion_querydailyhits"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryIndex",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                wagtail.contrib.routable_page.models.RoutablePageMixin,
                "wagtailcore.page",
            ),
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("include_comments", models.BooleanField(default=True)),
                (
                    "content",
                    wagtail.fields.StreamField(
                        [
                            ("head", 2),
                            ("blockquote", 4),
                            ("rich_text", 5),
                            ("image", 8),
                            ("table", 9),
                            ("code", 11),
                        ],
                        block_lookup={
                            0: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("h2", "head 2"),
                                        ("h3", "head 3"),
                                        ("h4", "head 4"),
                                    ],
                                    "max_length": 2,
                                },
                            ),
                            1: ("wagtail.blocks.CharBlock", (), {"max_length": 255}),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("head_type", 0), ("title", 1)]],
                                {},
                            ),
                            3: ("wagtail.blocks.TextBlock", (), {}),
                            4: ("wagtail.blocks.StructBlock", [[("text", 3)]], {}),
                            5: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "bold",
                                        "italic",
                                        "code",
                                        "ol",
                                        "ul",
                                        "link",
                                        "document-link",
                                    ]
                                },
                            ),
                            6: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            7: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 50, "required": False},
                            ),
                            8: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 6), ("caption", 7)]],
                                {},
                            ),
                            9: (
                                "wagtail.contrib.table_block.blocks.TableBlock",
                                (),
                                {},
                            ),
                            10: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("py", "Python"),
                                        ("js", "Javascript"),
                                        ("java", "Java"),
                                        ("html", "html"),
                                        ("dart", "Dart"),
                                        ("c", "C"),
                                    ]
                                },
                            ),
                            11: (
                                "wagtail.blocks.StructBlock",
                                [[("code_type", 10), ("code", 3)]],
                                {},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="PostCategory",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("description", wagtail.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=(
                wagtail.contrib.routable_page.models.RoutablePageMixin,
                "wagtailcore.page",
            ),
        ),
        migrations.CreateModel(
            name="PostPageTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_object",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tagged_items",
                        to="post.post",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_items",
                        to="taggit.tag",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="post.PostPageTag",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
