# Generated by Django 4.1.3 on 2022-11-05 11:34

from django.db import migrations
import wagtail.blocks
import wagtail.contrib.table_block.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    (
                        "head",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "head_type",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("h2", "head 2"),
                                            ("h3", "head 3"),
                                            ("h4", "head 4"),
                                        ],
                                        max_length=2,
                                    ),
                                ),
                                ("title", wagtail.blocks.CharBlock(max_length=255)),
                            ]
                        ),
                    ),
                    (
                        "blockquote",
                        wagtail.blocks.StructBlock(
                            [("text", wagtail.blocks.TextBlock())]
                        ),
                    ),
                    (
                        "rich_text",
                        wagtail.blocks.RichTextBlock(
                            features=[
                                "bold",
                                "italic",
                                "code",
                                "ol",
                                "ul",
                                "link",
                                "document-link",
                            ]
                        ),
                    ),
                    (
                        "image",
                        wagtail.blocks.StructBlock(
                            [
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                (
                                    "caption",
                                    wagtail.blocks.CharBlock(
                                        max_length=50, required=False
                                    ),
                                ),
                            ]
                        ),
                    ),
                    ("table", wagtail.contrib.table_block.blocks.TableBlock()),
                    (
                        "code",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "code_type",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("py", "Python"),
                                            ("js", "Javascript"),
                                            ("java", "Java"),
                                            ("html", "html"),
                                            ("dart", "Dart"),
                                            ("c", "C"),
                                        ]
                                    ),
                                ),
                                ("code", wagtail.blocks.TextBlock()),
                            ]
                        ),
                    ),
                ],
                use_json_field=True,
            ),
        ),
    ]
