# Generated by Django 5.0.8 on 2024-11-01 19:34

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0001_initial"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    ("head", 2),
                    ("blockquote", 4),
                    ("rich_text", 5),
                    ("image", 8),
                    ("table", 9),
                    ("code", 11),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("h2", "head 2"),
                                ("h3", "head 3"),
                                ("h4", "head 4"),
                            ],
                            "max_length": 2,
                        },
                    ),
                    1: ("wagtail.blocks.CharBlock", (), {"max_length": 255}),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("head_type", 0), ("title", 1)]],
                        {},
                    ),
                    3: ("wagtail.blocks.TextBlock", (), {}),
                    4: ("wagtail.blocks.StructBlock", [[("text", 3)]], {}),
                    5: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "code",
                                "ol",
                                "ul",
                                "link",
                                "document-link",
                            ]
                        },
                    ),
                    6: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 50, "required": False},
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 6), ("caption", 7)]],
                        {},
                    ),
                    9: ("wagtail.contrib.table_block.blocks.TableBlock", (), {}),
                    10: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("py", "Python"),
                                ("js", "Javascript"),
                                ("java", "Java"),
                                ("html", "html"),
                                ("dart", "Dart"),
                                ("shell", "Shell"),
                                ("bash", "Bash"),
                                ("c", "C"),
                                ("postgresql", "PostgreSQL"),
                            ]
                        },
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("code_type", 10), ("code", 3)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.CreateModel(
            name="PostCoverGalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("caption", models.CharField(blank=True, max_length=250)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_cover",
                        to="post.post",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
