# Generated by Django 4.0.6 on 2022-08-10 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_formpage_websiteinfosettings_socialmediasettings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediasettings',
            name='site',
        ),
        migrations.RemoveField(
            model_name='websiteinfosettings',
            name='side_logo',
        ),
        migrations.RemoveField(
            model_name='websiteinfosettings',
            name='site',
        ),
        migrations.RemoveField(
            model_name='websiteinfosettings',
            name='text_logo',
        ),
        migrations.DeleteModel(
            name='GoogleAnalyticsSettings',
        ),
        migrations.DeleteModel(
            name='SocialMediaSettings',
        ),
        migrations.DeleteModel(
            name='WebsiteInfoSettings',
        ),
    ]
