# Generated by Django 4.0.6 on 2022-07-29 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
        ('home', '0003_auto_20220729_2124'),
    ]

    operations = [
    ]
