# Generated by Django 4.1.3 on 2022-11-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_formpage_formfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formfield",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
