# Generated by Django 5.0.7 on 2024-08-06 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PageRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_name", models.CharField(max_length=500)),
                ("count", models.PositiveIntegerField()),
                ("create_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
