# Generated by Django 4.0.4 on 2022-08-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=500)),
                ('count', models.PositiveIntegerField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
