# Generated by Django 5.0.7 on 2024-08-06 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SubscribeUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_email", models.EmailField(max_length=254, verbose_name="email")),
                ("create_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
